/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import jy.library.*

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    val customLib = Library()
    customLib.PrintName("Josua")
}
